### ISSUE TITLE
example spec

### ISSUE THREAD

**Issue by jiusanzhou** [jiusanzhou/version#1]
```yaml version
version: v1.0.0
assets:
  android: https://cdn.zoe.im/assets/example-android-v1.0.0.apk
```

```json version
{

}
```
